spring:
  profiles:
    active: dev
  data:
    mongodb:
      username: spring
      password: spring
      host: localhost
      port: 27017
      database: SpringMGDB
  datasource:
    url: jdbc:mysql://localhost:3306/mybatics
    username: root
    password: LeNguyenKhoi21
  jpa:
    hibernate:
      ddl-auto: none

